module.exports={
    dbConfig: require('./dbConfig'),
    dbConnect: require('./sequelize'),
    MESSAGE: {
        OK:{
            code:0,
            message:'请求成功',
        },
        NON_TOKEN:{
            code:1,
            message:'无效令牌',
        },
        REGISTER_SUCCESS:{
            code:100,
            message:'注册成功',
        },
        ADD_SUCCESS:{
            code:101,
            message:"添加成功",
        },
        UPDATE_SUCCESS:{
            code:102,
            message:"修改成功",
        },
        USER_EXIST:{
            code:103,
            message:'用户已存在',
        },
        PASSWORD_ERROR:{
            code:300,
            message:'密码错误',
        },
        USER_NOT_EXIST: {
            code:404,
            message:'用户不存在',
        },
        AD_NOT_EXIST:{
            code:405,
            message:'管理员不存在',
        },
        AD_NOT_SUPER:{
            code:406,
            message:'非超级管理员没有权限',
        },
        DR_NOT_SUPER:{
            code:407,
            message:'非司机用户没有权限',
        },
        NON_ORDER:{
            code:501,
            message:'无效订单ID',
        },
        NON_FEEDBACK:{
            code:502,
            message:'无效反馈ID',
        },
        NON_COUPON:{
            code:503,
            message:'无效优惠券ID',
        },
        NON_NOTICE:{
            code:504,
            message:'无效公告ID',
        }
    }
}
